### ISSUE TITLE
Bug : import depuis PluXml 5.4

### ISSUE THREAD

**Issue by Draky50110** [benoitjpnet/PluXmlToWP#1]
Salut

Pas réussi à importer :/

Pour tester, j'ai un blog PluXml de test et voici le fichier XML de sortie du script : http://www.draky.net/blog2.xml et bon l'import est "failed" pour les 3 articles, visibles de base sur http://www.draky.net/pluxml/

Une idée @benpro ?

**Comment by benoitjpnet** [comment]
Salut,

J'ai pas touché à PluXml depuis des lustres et je n'ai pas le temps et ni l'envie de regarder le problème. Je suppose que depuis 1 an PluXml 5.4 a changé quelque chose qui casse ce script.

**Comment by Draky50110** [comment]
Pas de souci, je faisais juste remarquer :)
Je me doutais bien que ça foirait à cause de la diff. de version.
M'apprendra à tester des CMS peu utilisés ;)
Merci pour la réponse !
